_wandb:
    value:
        cli_version: 0.23.0
        e:
            ovwhd9a3quzfdepmwc8zkacuz9s3vyja:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "2147483648"
                codePath: train_model.py
                codePathLocal: train_model.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "458849189888"
                email: ds24m038@technikum-wien.at
                executable: /Users/sinahaghgoo/anaconda3/bin/python
                git:
                    commit: f4879bf8b9adb9e8979c91e5590b4bebab872625
                    remote: https://github.com/ds24m038/Solution-Deployment-Project.git
                host: 192.168.1.135
                memory:
                    total: "19327352832"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/sinahaghgoo/Library/CloudStorage/OneDrive-Persönlich/Solution Deployment/Project/train_model.py
                python: CPython 3.11.5
                root: /Users/sinahaghgoo/Library/CloudStorage/OneDrive-Persönlich/Solution Deployment/Project
                startedAt: "2025-12-02T14:34:35.230075Z"
                writerId: ovwhd9a3quzfdepmwc8zkacuz9s3vyja
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.5
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            test_confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: test_confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
dataset:
    value: Driver Drowsiness Dataset (DDD)
epochs:
    value: 10
input_size:
    value:
        - 227
        - 227
learning_rate:
    value: 0.001
model_architecture:
    value: DrowsinessCNN
num_classes:
    value: 2
optimizer:
    value: Adam
test_samples:
    value: 6270
total_parameters:
    value: 26211842
total_samples:
    value: 41793
train_samples:
    value: 29255
val_samples:
    value: 6268
